### ISSUE TITLE
Search for keywords on PMC database 

### ISSUE THREAD

**Issue by yucca-t-k** [pubannotation/pubannotation#1] opened 2016-05-17 01:40 UTC
The keyword search on PMC  searches for the keywords on PubMed DB.

Example:
* Search  
![search on PMC](https://cloud.githubusercontent.com/assets/6102021/15308528/87694a02-1c19-11e6-89fb-f590eec8b11b.png)

* Search Result
![Result](https://cloud.githubusercontent.com/assets/6102021/15308580/db9262f8-1c19-11e6-961c-5c1b92d0eff1.png)

* The first article is NOT in PMC (note the absence of PMCID)
![25897435](https://cloud.githubusercontent.com/assets/6102021/15308743/4899ddee-1c1b-11e6-9820-74ecf6a6ad30.png)

**Comment by jdkim** [comment] 2016-05-17 02:12
Thank you for reporting this problem.
There was a bug, and the search was not confined in the designated sourcedb.
The problem is now fixed.

**Closed by jdkim** 2016-05-17 02:12 UTC
Labels: bug
